homework1
WolfManR/GBStudyWebMVC pull request #1
Opened 2021-06-19 21:19 UTC by WolfManR

2021-06-24 13:59 UTC, vladimir-shmidt reviewed
посты скачиваюттся
немного не соответствует формат
в целом ок нужно немного улучшить

2021-06-24 13:59 UTC, vladimir-shmidt commented on src/SubTasks/HomeWork1/Program.cs
> +await WorkAsync(ApiUrl, PathToFile, true);
в целом для задания ок но данный код напоминает процедурный стиль. Лучше явно описывать классы создавать их и использовать

2021-06-24 13:59 UTC, vladimir-shmidt commented on src/SubTasks/HomeWork1/Program.cs
> +        return tasks.Select(x => x.Result);
при возврате из метода коллекции лучше материализовывать явно

2021-06-24 13:59 UTC, vladimir-shmidt commented on src/SubTasks/HomeWork1/Program.cs
> +        await JsonSerializer.SerializeAsync(stream, data, Options);
в целом для задания не критично но стандартная сериализация напишет в файл json что отличается от задания и потом зачем делать сериализацию json text -> class -> json text не проще тогда сразу напрямую текст писать?

2021-06-24 13:59 UTC, vladimir-shmidt commented on src/SubTasks/HomeWork1/Program.cs
> +        using var stream = GetFileStream(pathToFile);
await не зватает

2021-06-24 14:00 UTC, vladimir-shmidt requested changes

2021-06-24 14:00 UTC, vladimir-shmidt commented on src/SubTasks/HomeWork1/Program.cs
> +        return tasks.Select(x => x.Result);
также что будет если в посте id=5  произойдет ошибка?

2021-07-05 14:22 UTC, vladimir-shmidt approved these changes
задание ок
по общему подходу нужно больше практики. Помимо собственного напсания кода можно также почитать публичный репозитории крупных проектов что бы почуствовать стилистику и подходы

2021-07-05 14:22 UTC, vladimir-shmidt commented on src/SubTasks/HomeWork1/Program.cs
> +            if (id is 5 or 6) throw new InvalidOperationException("Fail");
данное поведение не соответствует реальному когда может произойти исключение при скачивании контента из-за отсутствия интернета например
в таком подхоже нужно возвращать Task.FromException https://docs.microsoft.com/ru-ru/dotnet/api/system.threading.tasks.task.fromexception?view=net-5.0

2021-07-05 14:22 UTC, vladimir-shmidt commented on src/SubTasks/HomeWork1/Program.cs
>      public static void InitializeClient(string baseApiUrl)
инициализация объекта должна происходить в конструкторе. В подходе с публичным методом InitializeClient - клиенты могут не вызвать что приведет к использованию класса с испорченным состоянием и нужно городить проверки флага инициализации что выглядит трешово

2021-07-05 17:11 UTC, WolfManR commented on src/SubTasks/HomeWork1/Program.cs
> +            if (id is 5 or 6) throw new InvalidOperationException("Fail");
использование Task.FromException возможно в методе без async

2021-07-05 21:02 UTC, vladimir-shmidt commented on src/SubTasks/HomeWork1/Program.cs
> +            if (id is 5 or 6) throw new InvalidOperationException("Fail");
вообще да
конкретно здесь метод async

2021-07-06 21:41 UTC, merged